=head1 NAME

Section

=head1 SYNOPSIS

    my $section = Section->new( "group", $description ); #Must pass these two parameters!
    my $description = Section->description;
    my $users = $section->Users;

=head1 DESCRIPTION

This is a class of B<Section::Group> which represents a group as defined
in a control file.

=head1 CONSTRUCTOR

    my $section->new( "group", $description );

The C<$description> is the description of this Group and is used for the
group name.

=head1 METHODS

=over 4

=item Description

    Sets/Gets description for the Group

=item Control_file

Sets/Gets the Control file that contains the sections. This is later
used for error processing. This must be a valid C<Control_file> object
type.

=item Control_file_line

Sets/Gets the line number that this section definition appeared in the
control file. This is later used for error processing. This must be a
type I<Integer>.

=item Users

Sets/Gets the list of users. Users are passed into this as a comma/space
separated string of users and groups. Groups start with an C<@> and users
don't. There is a special group C<@ALL> which all users are members.

This will return an array of all users and groups defined in this group.

=item Verify_parameters

Verifies that all parameters of a given group are correct, and that all
required parameters exist.

=back
